---
upload-to-database:
  import:
    - import:
        dirpath: ./data/
        file_extension: csv 
        prefix_filename: original_data

cleaned-upload-to-database:
  import:
    - import:
        dirpath: ./data/
        file_extension: csv 
        prefix_filename: sales
    - import:
        dirpath: ./data/
        file_extension: csv 
        prefix_filename: products

data_analysis_ext:
  export:
    - export:
        host: s3
        bucket_name: d2p.testing.bucket
        object_name: clv_data

modeling:
  export:
    - export:
        host: gsheet
        spread_sheet_id: 1h9V1yHMFfzS-CYz31xN4jzDUoWTaKOrCM2zuIsJykes
        worksheet_name: sales
